#!/bin/bash

notebook_dir=/tmp/ml-week
if [ ! -d $notebook_dir ]; then
    mkdir $notebook_dir;
fi
for f in $(find . -name talk.pdf); do
    cp $f $notebook_dir/$(dirname $f)_$(basename $f)
done

./collect-ipynb
