les_pauvres_gens = [
    "Il est nuit. La cabane est pauvre, mais bien close.",
    "Le logis est plein d'ombre et l'on sent quelque chose",
    "Qui rayonne à travers ce crépuscule obscur.",
    "Des filets de pêcheur sont accrochés au mur.",
    "Au fond, dans l'encoignure où quelque humble vaisselle",
    "Aux planches d'un bahut vaguement étincelle,",
    "On distingue un grand lit aux longs rideaux tombants.",
    "Tout près, un matelas s'étend sur de vieux bancs,",
    "Et cinq petits enfants, nid d'âmes, y sommeillent",
    "La haute cheminée où quelques flammes veillent",
    "Rougit le plafond sombre, et, le front sur le lit,",
    "Une femme à genoux prie, et songe, et pâlit.",
    "C'est la mère. Elle est seule. Et dehors, blanc d'écume,",
    "Au ciel, aux vents, aux rocs, à la nuit, à la brume,",
    "Le sinistre océan jette son noir sanglot.",

    "L'homme est en mer. Depuis l'enfance matelot,",
    "Il livre au hasard sombre une rude bataille.",
    "Pluie ou bourrasque, il faut qu'il sorte, il faut qu'il aille,",
    "Car les petits enfants ont faim. Il part le soir",
    "Quand l'eau profonde monte aux marches du musoir.",
    "Il gouverne à lui seul sa barque à quatre voiles.",
    "La femme est au logis, cousant les vieilles toiles,",
    "Remmaillant les filets, préparant l'hameçon,",
    "Surveillant l'âtre où bout la soupe de poisson,",
    "Puis priant Dieu sitôt que les cinq enfants dorment.",
    "Lui, seul, battu des flots qui toujours se reforment,",
    "l s'en va dans l'abîme et s'en va dans la nuit.",
    "Dur labeur ! tout est noir, tout est froid ; rien ne luit.",
    "Dans les brisants, parmi les lames en démence,",
    "L'endroit bon à la pêche, et, sur la mer immense,",
    "Le lieu mobile, obscur, capricieux, changeant,",
    "Où se plaît le poisson aux nageoires d'argent,",
    "Ce n'est qu'un point ; c'est grand deux fois comme la chambre.",
    "Or, la nuit, dans l'ondée et la brume, en décembre,",
    "Pour rencontrer ce point sur le désert mouvant,",
    "Comme il faut calculer la marée et le vent !",
    "Comme il faut combiner sûrement les manoeuvres !",
    "Les flots le long du bord glissent, vertes couleuvres ;",
    "Le gouffre roule et tord ses plis démesurés,",
    "Et fait râler d'horreur les agrès effarés.",
    "Lui, songe à sa Jeannie au sein des mers glacées,",
    "Et Jeannie en pleurant l'appelle ; et leurs pensées",
    "Se croisent dans la nuit, divins oiseaux du coeur.",

    "Elle prie, et la mauve au cri rauque et moqueur",
    "L'importune, et, parmi les écueils en décombres,",
    "L'océan l'épouvante, et toutes sortes d'ombres",
    "Passent dans son esprit : la mer, les matelots",
    "Emportés à travers la colère des flots ;",
    "Et dans sa gaine, ainsi que le sang dans l'artère,",
    "La froide horloge bat, jetant dans le mystère,",
    "Goutte à goutte, le temps, saisons, printemps, hivers ;",
    "Et chaque battement, dans l'énorme univers,",
    "Ouvre aux âmes, essaims d'autours et de colombes,",
    "D'un côté les berceaux et de l'autre les tombes.",

    "Elle songe, elle rêve. - Et tant de pauvreté !",
    "Ses petits vont pieds nus l'hiver comme l'été.",
    "Pas de pain de froment. On mange du pain d'orge.",
    "- Ô Dieu ! le vent rugit comme un soufflet de forge,",
    "La côte fait le bruit d'une enclume, on croit voir",
    "Les constellations fuir dans l'ouragan noir",
    "Comme les tourbillons d'étincelles de l'âtre.",
    "C'est l'heure où, gai danseur, minuit rit et folâtre",
    "Sous le loup de satin qu'illuminent ses yeux,",
    "Et c'est l'heure où minuit, brigand mystérieux,",
    "Voilé d'ombre et de pluie et le front dans la bise,",
    "Prend un pauvre marin frissonnant, et le brise",
    "Aux rochers monstrueux apparus brusquement.",
    "Horreur ! l'homme, dont l'onde éteint le hurlement,",
    "Sent fondre et s'enfoncer le bâtiment qui plonge ;",
    "Il sent s'ouvrir sous lui l'ombre et l'abîme, et songe",
    "Au vieil anneau de fer du quai plein de soleil !",

    "Ces mornes visions troublent son coeur, pareil",
    "A la nuit. Elle tremble et pleure.",

    "Ô pauvres femmes",
    "De pêcheurs ! c'est affreux de se dire : - Mes âmes,",
    "Père, amant, frère, fils, tout ce que j'ai de cher,",
    "C'est là, dans ce chaos ! mon coeur, mon sang, ma chair ! -",
    "Ciel ! être en proie aux flots, c'est être en proie aux bêtes.",
    "Oh ! songer que l'eau joue avec toutes ces têtes,",
    "Depuis le mousse enfant jusqu'au mari patron,",
    "Et que le vent hagard, soufflant dans son clairon,",
    "Dénoue au-dessus d'eux sa longue et folle tresse,",
    "Et que peut-être ils sont à cette heure en détresse,",
    "Et qu'on ne sait jamais au juste ce qu'ils font,",
    "Et que, pour tenir tête à cette mer sans fond,",
    "A tous ces gouffres d'ombre où ne luit nulle étoile,",
    "Es n'ont qu'un bout de planche avec un bout de toile !",
    "Souci lugubre ! on court à travers les galets,",
    "Le flot monte, on lui parle, on crie : Oh ! rends-nous-les !",
    "Mais, hélas ! que veut-on que dise à la pensée",
    "Toujours sombre, la mer toujours bouleversée !",

    "Jeannie est bien plus triste encor. Son homme est seul !",
    "Seul dans cette âpre nuit ! seul sous ce noir linceul !",
    "Pas d'aide. Ses enfants sont trop petits. - Ô mère !",
    "Tu dis : S'ils étaient grands ! - leur père est seul ! Chimère !",
    "Plus tard, quand ils seront près du père et partis,",
    "Tu diras en pleurant : Oh! s'ils étaient petits !",


    "Elle prend sa lanterne et sa cape. - C'est l'heure",
    "D'aller voir s'il revient, si la mer est meilleure,",
    "S'il fait jour, si la flamme est au mât du signal.",
    "Allons ! - Et la voilà qui part. L'air matinal",
    "Ne souffle pas encor. Rien. Pas de ligne blanche",
    "Dans l'espace où le flot des ténèbres s'épanche.",
    "Il pleut. Rien n'est plus noir que la pluie au matin ;",
    "On dirait que le jour tremble et doute, incertain,",
    "Et qu'ainsi que l'enfant, l'aube pleure de naître.",
    "Elle va. L'on ne voit luire aucune fenêtre.",

    "Tout à coup, a ses yeux qui cherchent le chemin,",
    "Avec je ne sais quoi de lugubre et d'humain",
    "Une sombre masure apparaît, décrépite ;",
    "Ni lumière, ni feu ; la porte au vent palpite ;",
    "Sur les murs vermoulus branle un toit hasardeux ;",
    "La bise sur ce toit tord des chaumes hideux,",
    "Jaunes, sales, pareils aux grosses eaux d'un fleuve.",

    "Tiens ! je ne pensais plus à cette pauvre veuve,",
    "Dit-elle ; mon mari, l'autre jour, la trouva",
    "Malade et seule ; il faut voit comment elle va.",

    "Elle frappe à la porte, elle écoute ; personne",
    "Ne répond. Et Jeannie au vent de mer frissonne.",
    "Malade ! Et ses enfants ! comme c'est mal nourri !",
    "Elle n'en a que deux, mais elle est sans mari.",
    "Puis, elle frappe encore. Hé ! voisine ! Elle appelle.",
    "Et la maison se tait toujours. Ah ! Dieu ! dit-elle,",
    "Comme elle dort, qu'il faut l'appeler si longtemps!",
    "La porte, cette fois, comme si, par instants,",
    "Les objets étaient pris d'une pitié suprême,",
    "Morne, tourna dans l'ombre et s'ouvrit d'elle-même.",

    "Elle entra. Sa lanterne éclaira le dedans",
    "Du noir logis muet au bord des flots grondants.",
    "L'eau tombait du plafond comme des trous d'un crible.",

    "Au fond était couchée une forme terrible ;",
    "Une femme immobile et renversée, ayant",
    "Les pieds nus, le regard obscur, l'air effrayant ;",
    "Un cadavre ; - autrefois, mère joyeuse et forte ; -",
    "Le spectre échevelé de la misère morte ;",
    "Ce qui reste du pauvre après un long combat.",
    "Elle laissait, parmi la paille du grabat,",
    "Son bras livide et froid et sa main déjà verte",
    "Pendre, et l'horreur sortait de cette bouche ouverte",
    "D'où l'âme en s'enfuyant, sinistre, avait jeté",
    "Ce grand cri de la mort qu'entend l'éternité !",

    "Près du lit où gisait la mère de famille,",
    "Deux tout petits enfants, le garçon et la fille,",
    "Dans le même berceau souriaient endormis.",

    "La mère, se sentant mourir, leur avait mis",
    "Sa mante sur les pieds et sur le corps sa robe,",
    "Afin que, dans cette ombre où la mort nous dérobe,",
    "Ils ne sentissent pas la tiédeur qui décroît,",
    "Et pour qu'ils eussent chaud pendant qu'elle aurait froid.",


    "Comme ils dorment tous deux dans le berceau qui tremble !",
    "Leur haleine est paisible et leur front calme. Il semble",
    "Que rien n'éveillerait ces orphelins dormant,",
    "Pas même le clairon du dernier jugement ;",
    "Car, étant innocents, ils n'ont pas peur du juge.",

    "Et la pluie au dehors gronde comme un déluge.",
    "Du vieux toit crevassé, d'où la rafale sort,",
    "Une goutte parfois tombe sur ce front mort,",
    "Glisse sur cette joue et devient une larme.",
    "La vague sonne ainsi qu'une cloche d'alarme.",
    "La morte écoute l'ombre avec stupidité.",
    "Car le corps, quand l'esprit radieux l'a quitté,",
    "A l'air de chercher l'âme et de rappeler l'ange ;",
    "Il semble qu'on entend ce dialogue étrange",
    "Entre la bouche pâle et l'oeil triste et hagard :",
    "- Qu'as-tu fait de ton souffle ? - Et toi, de ton regard ?",

    "Hélas! aimez, vivez, cueillez les primevères,",
    "Dansez, riez, brûlez vos coeurs, videz vos verres.",
    "Comme au sombre océan arrive tout ruisseau,",
    "Le sort donne pour but au festin, au berceau,",
    "Aux mères adorant l'enfance épanouie,",
    "Aux baisers de la chair dont l'âme est éblouie,",
    "Aux chansons, au sourire, à l'amour frais et beau,",
    "Le refroidissement lugubre du tombeau !",


    "Qu'est-ce donc que Jeannie a fait chez cette morte ?",
    "Sous sa cape aux longs plis qu'est-ce donc qu'elle emporte ?",
    "Qu'est-ce donc que Jeannie emporte en s'en allant ?",
    "Pourquoi son coeur bat-il ? Pourquoi son pas tremblant",
    "Se hâte-t-il ainsi ? D'où vient qu'en la ruelle",
    "Elle court, sans oser regarder derrière elle ?",
    "Qu'est-ce donc qu'elle cache avec un air troublé",
    "Dans l'ombre, sur son lit ? Qu'a-t-elle donc volé ?",


    "Quand elle fut rentrée au logis, la falaise",
    "Blanchissait; près du lit elle prit une chaise",
    "Et s'assit toute pâle ; on eût dit qu'elle avait",
    "Un remords, et son front tomba sur le chevet,",
    "Et, par instants, à mots entrecoupés, sa bouche",
    "Parlait pendant qu'au loin grondait la mer farouche.",

    "Mon pauvre homme ! ah ! mon Dieu ! que va-t-il dire ? Il a",
    "Déjà tant de souci ! Qu'est-ce que j'ai fait là ?",
    "Cinq enfants sur les bras ! ce père qui travaille !",
    "Il n'avait pas assez de peine ; il faut que j'aille",
    "Lui donner celle-là de plus. - C'est lui ? - Non. Rien.",
    "- J'ai mal fait. - S'il me bat, je dirai : Tu fais bien.",
    "- Est-ce lui ? - Non. - Tant mieux. - La porte bouge comme",
    "Si l'on entrait. - Mais non. - Voilà-t-il pas, pauvre homme,",
    "Que j'ai peur de le voir rentrer, moi, maintenant !",
    "Puis elle demeura pensive et frissonnant,",
    "S'enfonçant par degrés dans son angoisse intime,",
    "Perdue en son souci comme dans un abîme,",
    "N'entendant même plus les bruits extérieurs,",
    "Les cormorans qui vont comme de noirs crieurs,",
    "Et l'onde et la marée et le vent en colère.",

    "La porte tout à coup s'ouvrit, bruyante et claire,",
    "Et fit dans la cabane entrer un rayon blanc ;",
    "Et le pêcheur, traînant son filet ruisselant,",
    "Joyeux, parut au seuil, et dit : C'est la marine !",


    "C'est toi ! cria Jeannie, et, contre sa poitrine,",
    "Elle prit son mari comme on prend un amant,",
    "Et lui baisa sa veste avec emportement",
    "Tandis que le marin disait : Me voici, femme !",
    "Et montrait sur son front qu'éclairait l'âtre en flamme",
    "Son coeur bon et content que Jeannie éclairait,",
    "Je suis volé, dit-il ; la mer c'est la forêt.",
    "- Quel temps a-t-il fait ? - Dur. - Et la pêche ? - Mauvaise.",
    "Mais, vois-tu, je t 1 embrasse, et me voilà bien aise.",
    "Je n'ai rien pris du tout. J'ai troué mon filet.",
    "Le diable était caché dans le vent qui soufflait.",
    "Quelle nuit ! Un moment, dans tout ce tintamarre,",
    "J'ai cru que le bateau se couchait, et l'amarre",
    "A cassé. Qu'as-tu fait, toi, pendant ce temps-là ?",
    "Jeannie eut un frisson dans l'ombre et se troubla.",
    "Moi ? dit-elle. Ah ! mon Dieu ! rien, comme à l'ordinaire,",
    "J'ai cousu. J'écoutais la mer comme un tonnerre,",
    "J'avais peur. - Oui, l'hiver est dur, mais c'est égal.",
    "Alors, tremblante ainsi que ceux qui font le mal,",
    "Elle dit : A propos, notre voisine est morte.",
    "C'est hier qu'elle a dû mourir, enfin, n'importe,",
    "Dans la soirée, après que vous fûtes partis.",
    "Elle laisse ses deux enfants, qui sont petits.",
    "L'un s'appelle Guillaume et l'autre Madeleine ;",
    "L'un qui ne marche pas, l'autre qui parle à peine.",
    "La pauvre bonne femme était dans le besoin.",

    "L'homme prit un air grave, et, jetant dans un coin",
    "Son bonnet de forçat mouillé par la tempête :",
    "Diable ! diable ! dit-il, en se grattant la tête,",
    "Nous avions cinq enfants, cela va faire sept.",
    "Déjà, dans la saison mauvaise, on se passait",
    "De souper quelquefois. Comment allons-nous faire ?",
    "Bah ! tant pis ! ce n'est pas ma faute, C'est l'affaire",
    "Du bon Dieu. Ce sont là des accidents profonds.",
    "Pourquoi donc a-t-il pris leur mère à ces chiffons ?",
    "C'est gros comme le poing. Ces choses-là sont rudes.",
    "Il faut pour les comprendre avoir fait ses études.",
    "Si petits ! on ne peut leur dire : Travaillez.",
    "Femme, va les chercher. S'ils se sont réveillés,",
    "Ils doivent avoir peur tout seuls avec la morte.",
    "C'est la mère, vois-tu, qui frappe à notre porte ;",
    "Ouvrons aux deux enfants. Nous les mêlerons tous,",
    "Cela nous grimpera le soir sur les genoux.",
    "Ils vivront, ils seront frère et soeur des cinq autres.",
    "Quand il verra qu'il faut nourrir avec les nôtres",
    "Cette petite fille et ce petit garçon,",
    "Le bon Dieu nous fera prendre plus de poisson.",
    "Moi, je boirai de l'eau, je ferai double tâche,",
    "C'est dit. Va les chercher. Mais qu'as-tu ? Ça te fâche ?",
    "D'ordinaire, tu cours plus vite que cela.",

    "- Tiens, dit-elle en ouvrant les rideaux, lès voilà!"
]
