// Server

int32_t add(const int32_t n1,
            const int32_t n2) { ...

int32_t calculate(const int32_t logid,
                  const Work& work) { ...

void getStruct(SharedStruct& ret,
               const int32_t logid) { ...

void zip() { ...
